"""
scorer.py — LLM intent scoring via Groq API (free tier).
Uses compressed CANDIDATE_PROFILE to minimize token usage.
Profile loaded from config/profile.json (generated by setup_profile.py).
"""

import json
import time
import logging
from pathlib import Path
from groq import Groq

log = logging.getLogger(__name__)

SCORING_MODEL = "llama-3.3-70b-versatile"
_PROFILE_PATH = Path(__file__).parent / "config" / "profile.json"


def _load_profiles() -> tuple:
    """
    Returns (compressed_prompt, full_prompt).
    compressed_prompt used in every scoring batch (low token cost ~60 tokens).
    full_prompt used in verifier only (called once per run, more detail).
    """
    if _PROFILE_PATH.exists():
        try:
            data       = json.loads(_PROFILE_PATH.read_text(encoding="utf-8"))
            compressed = data.get("_scoring_prompt", "")
            full       = data.get("_full_profile", "")
            if compressed:
                log.info(
                    f"Profile loaded from profile.json "
                    f"(~{len(compressed.split())} tokens compressed, "
                    f"~{len(full.split())} tokens full)"
                )
                return compressed, full
        except Exception as e:
            log.warning(f"Could not load profile.json: {e} — using fallback")

    log.info("Using hardcoded fallback profile. Run setup_profile.py to use your resume.")
    fallback = (
        "Sam, YCCE Nagpur CSE 2027 fresher, CGPA 7.9, GenAI intern.\n"
        "Skills: LangChain RAG ChromaDB XGBoost FastAPI Python Java AWS Docker CrewAI.\n"
        "Projects: Financial RAG, Credit Risk ML, WebSocket backend SIH, Job Intel Agent.\n"
        "Wants: GenAI/ML/SDE/Backend at product co or AI startup. 0-2yr exp. India.\n"
        "Veto: TCS/Infosys/Wipro/Accenture/HCL(no AI title), 3+yr req, DevOps/Sales/Hardware."
    )
    return fallback, fallback


# Load once at module level
CANDIDATE_PROFILE, CANDIDATE_PROFILE_FULL = _load_profiles()


# Compressed scoring system — ~130 tokens total
SCORING_SYSTEM = """Score jobs AND internships for this candidate. INTENT matching only, not keywords.

CANDIDATE wants: full-time fresher roles AND paid internships (especially with PPO/stipend).
Both job types are equally valid. Internship at Google/Amazon/top startup = HIGH.

AXES (100pts total):
role(30): GenAI/LLM=30 ML=25 SDE@AI-co=20 SDE=14 DevOps=3
skills(30): Python+LLM/ML=28 Python+backend=20 irrelevant=2
level(25): intern/fresher/entry/0-1yr=25 0-2yr=20 0-3yr=12 3+yr required=0
company(15): top-product/AI-startup=15 mid-product=10 IT-services=2

PRIORITY: 80+=HIGH 60-79=MEDIUM 40-59=LOW <40=SKIP

VETO to SKIP: TCS/Infosys/Wipro/Accenture/HCL without AI/ML in title | 3+yr no intern/fresher mention | pure DevOps/Sales/Hardware | non-India non-remote | unpaid internship

Return ONLY valid JSON array, no markdown, no explanation:
[{"job_id":"...","relevance_score":0-100,"score_breakdown":{"role":0,"skills":0,"level":0,"company":0},"match_reason":"1 sentence","key_match_skills":["s1"],"red_flags":[],"priority":"HIGH|MEDIUM|LOW|SKIP"}]"""


def _clean(raw: str) -> str:
    """Strip markdown fences from model output."""
    if "```" in raw:
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:].strip()
    return raw.strip()


def score_jobs_with_llm(
    jobs: list,
    api_key: str,
    batch_size: int = 20,
) -> list:
    """
    Score jobs using Groq llama-3.3-70b-versatile.
    Token budget per batch of 20:
      system prompt  ~130 tokens
      candidate      ~60 tokens
      20 jobs        ~25 tokens each = 500 tokens
      TOTAL INPUT    ~690 tokens per batch
    For 100 jobs = 5 batches = ~3,450 tokens total. Well within 12k TPM limit.
    """
    if not jobs:
        return []

    if not api_key:
        log.error("groq_api_key missing — cannot score.")
        return []

    client        = Groq(api_key=api_key)
    results       = []
    total_batches = -(-len(jobs) // batch_size)

    log.info(
        f"Scoring {len(jobs)} jobs | {total_batches} batches of {batch_size} | "
        f"est. ~{total_batches * 700:,} input tokens"
    )

    for i in range(0, len(jobs), batch_size):
        batch     = jobs[i : i + batch_size]
        batch_num = i // batch_size + 1
        log.info(f"  Batch {batch_num}/{total_batches} ({len(batch)} jobs)...")

        # Minimal payload — title + company is 90% of scoring signal
        # desc trimmed to 100 chars for edge cases where title is ambiguous
        payload = [
            {
                "id":      j["job_id"],
                "title":   j["title"],
                "company": j["company"],
                "loc":     (j.get("location") or "")[:30],
                "desc":    (j.get("description") or "")[:100],
            }
            for j in batch
        ]

        try:
            response = client.chat.completions.create(
                model=SCORING_MODEL,
                messages=[
                    {"role": "system", "content": SCORING_SYSTEM},
                    {
                        "role": "user",
                        "content": (
                            f"CANDIDATE: {CANDIDATE_PROFILE}\n\n"
                            f"JOBS: {json.dumps(payload)}\n\n"
                            "JSON array only."
                        ),
                    },
                ],
                temperature=0.1,
                max_tokens=2048,
            )

            raw    = response.choices[0].message.content.strip()
            raw    = _clean(raw)
            scores = json.loads(raw)

            # Note: payload uses "id" key, scores use "job_id"
            score_map = {s.get("job_id", s.get("id", "")): s for s in scores}
            passed = skipped = 0

            for job in batch:
                s = score_map.get(job["job_id"])
                if not s:
                    continue
                if s.get("priority", "SKIP") == "SKIP":
                    skipped += 1
                    continue
                job["relevance_score"]  = int(s.get("relevance_score", 0))
                job["score_breakdown"]  = s.get("score_breakdown", {})
                job["match_reason"]     = s.get("match_reason", "")
                job["key_match_skills"] = s.get("key_match_skills", [])
                job["red_flags"]        = s.get("red_flags", [])
                job["priority"]         = s.get("priority", "LOW")
                results.append(job)
                passed += 1

            log.info(f"    -> {passed} relevant, {skipped} skipped")

        except json.JSONDecodeError as e:
            log.error(f"  JSON parse error batch {batch_num}: {e}")
            log.debug(f"  Raw: {raw[:200]}")
        except Exception as e:
            log.error(f"  Groq error batch {batch_num}: {e}")
            if "rate_limit" in str(e).lower():
                log.info("  Rate limit hit — waiting 60s then retrying...")
                time.sleep(60)
                try:
                    response = client.chat.completions.create(
                        model=SCORING_MODEL,
                        messages=[
                            {"role": "system", "content": SCORING_SYSTEM},
                            {
                                "role": "user",
                                "content": (
                                    f"CANDIDATE: {CANDIDATE_PROFILE}\n\n"
                                    f"JOBS: {json.dumps(payload)}\n\n"
                                    "JSON array only."
                                ),
                            },
                        ],
                        temperature=0.1,
                        max_tokens=2048,
                    )
                    raw    = response.choices[0].message.content.strip()
                    raw    = _clean(raw)
                    scores = json.loads(raw)
                    score_map = {s.get("job_id", s.get("id", "")): s for s in scores}
                    for job in batch:
                        s = score_map.get(job["job_id"])
                        if not s or s.get("priority", "SKIP") == "SKIP":
                            continue
                        job["relevance_score"]  = int(s.get("relevance_score", 0))
                        job["score_breakdown"]  = s.get("score_breakdown", {})
                        job["match_reason"]     = s.get("match_reason", "")
                        job["key_match_skills"] = s.get("key_match_skills", [])
                        job["red_flags"]        = s.get("red_flags", [])
                        job["priority"]         = s.get("priority", "LOW")
                        results.append(job)
                except Exception as e2:
                    log.error(f"  Retry failed: {e2}")

        if batch_num < total_batches:
            time.sleep(2)

    log.info(f"Scoring done — {len(results)} relevant from {len(jobs)} jobs")
    return results