"""
scorer.py — Job scoring via Groq API (fast, free 14k req/day).
Ollama is NOT used here — Groq handles the heavy LLM scoring work.
"""

import json
import time
import re
import logging
from pathlib import Path
from groq import Groq

log = logging.getLogger(__name__)

SCORING_MODEL = "llama-3.3-70b-versatile"

# ── Load profile dynamically ──────────────────────────────────────────────────
_PROFILE_PATH = Path(__file__).parent / "config" / "profile.json"

def _load_candidate_profile() -> str:
    """
    Load profile from config/profile.json if it exists (generated by setup_profile.py).
    Falls back to the hardcoded profile if not yet generated.
    """
    if _PROFILE_PATH.exists():
        try:
            data = json.loads(_PROFILE_PATH.read_text(encoding="utf-8"))
            prompt = data.get("_scoring_prompt", "")
            if prompt:
                log.info("Loaded candidate profile from config/profile.json")
                return prompt
        except Exception as e:
            log.warning(f"Could not load profile.json: {e} — using fallback")

    # Fallback hardcoded profile
    log.info("Using hardcoded candidate profile (run setup_profile.py to use your resume)")
    return """
Name: Shashwat Mahajan (Sam)
College: YCCE Nagpur — B.Tech Computer Science, graduating June 2027
CGPA: ~7.9. Currently interning as GenAI Engineer.
Skills: LangChain, RAG, ChromaDB, XGBoost, FastAPI, Python, Java, AWS S3, Docker, CrewAI.
Projects: Financial RAG System, Credit Risk ML Pipeline, WebSocket backend (SIH), Job Intel Agent.
Target roles: GenAI Engineer, ML Engineer, SDE at AI company, Backend Engineer.
Must be: fresher/entry-level (0-2 yrs), India, product company or AI startup.
Vetoes: TCS/Infosys/Wipro/Accenture/HCL (unless title has AI/ML), 3+ yrs required, DevOps/sales.
"""

CANDIDATE_PROFILE = _load_candidate_profile()

SCORING_SYSTEM = """
You are a technical recruiter scoring job listings for a specific candidate.
Do INTENT-BASED matching — judge what the job actually involves, not just its title.

SCORING AXES (total = 100):
1. Role alignment (0-30): GenAI/LLM=30, ML Eng=25, SDE at AI co=20, general SDE=14, DevOps/hardware=3
2. Skill match (0-30): Python+LLM/ML=28, Python+APIs+backend=20, irrelevant stack=2
3. Level fit (0-25): fresher/entry/campus/0-1yr=25, 0-2yr=20, 0-3yr=12, 3+yr required=0
4. Company fit (0-15): top product/AI startup=15, mid-tier product=10, IT services=2

PRIORITY: 80-100=HIGH, 60-79=MEDIUM, 40-59=LOW, 0-39=SKIP

HARD VETO — immediately score=0, priority=SKIP if ANY of these:
- IT outsourcing (TCS/Infosys/Wipro/Accenture/Cognizant/HCL) AND title has no AI/ML/GenAI
- Requires 3+ years, no fresher mention
- Pure DevOps, Network, Hardware, Sales
- Outside India and not remote

Return ONLY a valid JSON array. No explanation, no markdown, no extra text.
Schema:
[{"job_id":"...","relevance_score":0-100,"score_breakdown":{"role":0-30,"skills":0-30,"level":0-25,"company":0-15},"match_reason":"2-3 sentences","key_match_skills":["skill1"],"red_flags":["flag if any"],"priority":"HIGH|MEDIUM|LOW|SKIP"}]
"""


def _clean(raw: str) -> str:
    """Strip markdown fences from model output."""
    if "```" in raw:
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:].strip()
    return raw.strip()


def score_jobs_with_llm(
    jobs: list,
    api_key: str,
    batch_size: int = 15,
) -> list:
    """
    Score jobs using Groq llama-3.3-70b-versatile.
    Returns only jobs with priority != SKIP, enriched with score fields.
    """
    if not jobs:
        return []

    if not api_key:
        log.error("groq_api_key missing — cannot score jobs.")
        return []

    client        = Groq(api_key=api_key)
    results       = []
    total_batches = -(-len(jobs) // batch_size)

    for i in range(0, len(jobs), batch_size):
        batch     = jobs[i : i + batch_size]
        batch_num = i // batch_size + 1
        log.info(f"  Scoring batch {batch_num}/{total_batches} ({len(batch)} jobs)...")

        payload = [
            {
                "job_id":      j["job_id"],
                "title":       j["title"],
                "company":     j["company"],
                "location":    j.get("location", ""),
                "description": (j.get("description") or "")[:500],
                "source":      j.get("source", ""),
            }
            for j in batch
        ]

        try:
            response = client.chat.completions.create(
                model=SCORING_MODEL,
                messages=[
                    {"role": "system", "content": SCORING_SYSTEM},
                    {
                        "role": "user",
                        "content": (
                            f"CANDIDATE PROFILE:\n{CANDIDATE_PROFILE}\n\n"
                            f"SCORE THESE {len(batch)} JOBS:\n"
                            f"{json.dumps(payload, indent=2)}\n\n"
                            "Return JSON array only."
                        ),
                    },
                ],
                temperature=0.1,
                max_tokens=4096,
            )

            raw    = response.choices[0].message.content.strip()
            raw    = _clean(raw)
            scores = json.loads(raw)

            score_map = {s["job_id"]: s for s in scores}
            passed = skipped = 0

            for job in batch:
                s = score_map.get(job["job_id"])
                if not s:
                    continue
                if s.get("priority", "SKIP") == "SKIP":
                    skipped += 1
                    continue
                job["relevance_score"]  = int(s.get("relevance_score", 0))
                job["score_breakdown"]  = s.get("score_breakdown", {})
                job["match_reason"]     = s.get("match_reason", "")
                job["key_match_skills"] = s.get("key_match_skills", [])
                job["red_flags"]        = s.get("red_flags", [])
                job["priority"]         = s.get("priority", "LOW")
                results.append(job)
                passed += 1

            log.info(f"    Batch {batch_num}: {passed} relevant, {skipped} skipped")

        except json.JSONDecodeError as e:
            log.error(f"  JSON parse error batch {batch_num}: {e}")
            log.debug(f"  Raw: {raw[:300]}")
        except Exception as e:
            log.error(f"  Groq error batch {batch_num}: {e}")
            # Rate limit — wait and retry once
            if "rate_limit" in str(e).lower():
                log.info("  Rate limit hit — waiting 60s then retrying...")
                time.sleep(60)
                try:
                    response = client.chat.completions.create(
                        model=SCORING_MODEL,
                        messages=[
                            {"role": "system", "content": SCORING_SYSTEM},
                            {
                                "role": "user",
                                "content": (
                                    f"CANDIDATE PROFILE:\n{CANDIDATE_PROFILE}\n\n"
                                    f"SCORE THESE {len(batch)} JOBS:\n"
                                    f"{json.dumps(payload, indent=2)}\n\n"
                                    "Return JSON array only."
                                ),
                            },
                        ],
                        temperature=0.1,
                        max_tokens=4096,
                    )
                    raw    = response.choices[0].message.content.strip()
                    raw    = _clean(raw)
                    scores = json.loads(raw)
                    score_map = {s["job_id"]: s for s in scores}
                    for job in batch:
                        s = score_map.get(job["job_id"])
                        if not s or s.get("priority", "SKIP") == "SKIP":
                            continue
                        job["relevance_score"]  = int(s.get("relevance_score", 0))
                        job["score_breakdown"]  = s.get("score_breakdown", {})
                        job["match_reason"]     = s.get("match_reason", "")
                        job["key_match_skills"] = s.get("key_match_skills", [])
                        job["red_flags"]        = s.get("red_flags", [])
                        job["priority"]         = s.get("priority", "LOW")
                        results.append(job)
                except Exception as e2:
                    log.error(f"  Retry also failed: {e2}")

        # Groq free tier — small delay between batches
        if batch_num < total_batches:
            time.sleep(3)

    log.info(f"Scoring done — {len(results)} relevant from {len(jobs)} jobs")
    return results